FROM spark:3.5.1

# Copy PySpark script
COPY pysparkexample.py /app/pysparkexample.py

# Install required libraries (if needed)
# Use RUN pip install <package_name> for specific library installation

# Set working directory
WORKDIR /app